blog_name = "既来之，则安之"
github = "https://github.com/chanyon"
output = "dist"
[template]
about = "content/template/about.pd"
footer = "content/template/footer.pd"
[[menus]]
name = "Home" 
url = "/home"
[[menus]]
name = "About"
url = "/about"
[[issues]]
title = "随记"
path = "content/issue-1"
[[issues]]
title = "Rust"
path = "content/issue-2"