[[articles]]
file = "1-first.md"
title = "first article"
author = ""
pub_date = "2023-02-17"
[[articles]]
file = "3-TS_type.md"
title = "TS类型体操笔记"
author = ""
pub_date = "2023-04-16"
[[articles]]
file = "2-cmake_learn.md"
title = "学习 CMAKE 笔记"
author = ""
pub_date = "2023-08-05"
[[articles]]
file = "4-compiler.md"
title = "编译器设计读书笔记"
author = ""
pub_date = "2023-10-24"
[[articles]]
file = "5-zig_link_library.md"
title = "zig_link_library"
author = ""
pub_date = "2023-11-09"
[[articles]]
file = "6-windows-app.md"
title = "自用Windows应用与工具"
author = "dcy"
pub_date = "2024-03-07"